Docs and examples
ApexAI/apex_rostest pull request #10
Opened 2019-02-19 23:20 UTC by pbaughman

Improve the documentation and examples to make it a little easier to get started with apex_launchtest

#### Depends on
 - https://github.com/ApexAI/apex_rostest/pull/6
 - https://github.com/ApexAI/apex_rostest/pull/8

#### Todo:
- [ ] Have a list of asserts similar to https://docs.python.org/2/library/unittest.html#assert-methods.  Maybe blocked on https://github.com/ApexAI/apex_rostest/issues/7
- [ ] Describe in more detail how arguments are passed into the launch description and into the tests

2019-02-20 22:26 UTC, dejanpan commented on README.md
> +# apex_launchtest
Please add `#Compatibility` section:

`apex_rostest` currently works with ros2 latest (master) release.

2019-02-21 18:36 UTC, pbaughman commented on README.md
> +# apex_launchtest
@dejanpan done

2019-02-25 18:27 UTC, pbaughman commented
@dejanpan This is done.  Can you review and approve #16 and then this PR?

2019-02-28 02:12 UTC, dejanpan requested changes

2019-02-28 02:12 UTC, dejanpan commented on README.md
> +```
add py for better syntax highlighting?

2019-02-28 02:12 UTC, dejanpan commented on README.md
> +It should also call the ready_fn that is passed in to signal when the tests should start.  In the good_proc.test.py example, there
ready_fn => `ready_fn`

2019-02-28 02:12 UTC, dejanpan commented on README.md
> +is no need to delay the start of the tests so the ready_fn is called concurrently when the launching of the process under test
ready_fn => `ready_fn`

2019-02-28 02:12 UTC, dejanpan commented on README.md
> + * self.proc_info - a [ProcInfoHandler object](apex_launchtest/proc_info_handler)
this path is actually "apex_launchtest/apex_launchtest/proc_info_handler.py"

2019-02-28 02:12 UTC, dejanpan commented on README.md
> + * self.proc_output - an [IoHandler object](apex_launchtest/io_handler.py)
this path is "apex_launchtest/apex_launchtest/io_handler.py"

2019-02-28 02:12 UTC, dejanpan commented on README.md
> +by one of several assert methods to check the output or exit codes of the process
:

2019-02-28 02:12 UTC, dejanpan commented on README.md
> +The ActiveTests can also call methods that wait for particular output or a particular process to exit or time out.  These asserts are methods on the proc_output and proc_info objects
proc_output => `proc_output`

proc_info => `proc_info`

2019-02-28 02:12 UTC, dejanpan commented on README.md
> +`proc_info.assertWaitForShutdown(proc, cmd_args=None, *, timeout=10)
` missing at the end

2019-02-28 02:12 UTC, dejanpan commented on README.md
> +
Could we maybe list couple things that you can test with this framework, e.g.:
1. the process/node under test started and shutdown correctly
1. two or more nodes under test successfully established ros topic connection
1. the process/node under test died unexpectedly
1. the process/node received the data and published the result on stdout or ros topic
1. the process/node received the right arguments
1. ...

2019-02-28 02:13 UTC, dejanpan commented
@pbaughman couple of suggestions after the review.

2019-02-28 17:24 UTC, pbaughman commented on README.md
> +`proc_info.assertWaitForShutdown(proc, cmd_args=None, *, timeout=10)
Oops!

2019-02-28 17:29 UTC, pbaughman commented
@dejanpan Ok, I think that addresses your comments

2019-03-01 01:54 UTC, dejanpan commented on README.md
> + * self.proc_info - a [ProcInfoHandler object](apex_launchtest/proc_info_handler)
.py extension is missing in the file name

2019-03-01 01:55 UTC, dejanpan commented on README.md
> +  * Some tests run concurrnetly with the launch and can interact with the running processes.
concurrnetly => concurrently

2019-03-01 01:55 UTC, pbaughman commented
Gah!  Ok sorry.  I will fix




On Thu, Feb 28, 2019 at 5:54 PM -0800, "Dejan Pangercic" <notifications@github.com> wrote:












@dejanpan commented on this pull request.





In README.md:
> +It should also call the ready_fn that is passed in to signal when the tests should start.  In the good_proc.test.py example, there
+is no need to delay the start of the tests so the ready_fn is called concurrently when the launching of the process under test
+
+#### Active Tests
+Any classes that inherit from unittest.TestCase and not decorated with the post_shutdown_test descriptor will be run concurrently
+with the proccess under test.  These tests are expected to interact with the running processes in some way
+
+#### Post-Shutdown Tests
+Any classes that inherit from unittest.TestCase that are decorated with the post_shutdown_test descriptor will be run after the launched
+processes have been shut down.  These tests have access to the exit codes and the stdout of all of the launched processes, as well
+as any data created as a side-effect of running the processes
+
+#### Exit Codes and Standard Out
+the apex_launchtest framework automatically adds some member fields to each test case so that the tests can access process output and exit codes
+
+ * self.proc_info - a [ProcInfoHandler object](apex_launchtest/proc_info_handler)



.py extension is missing in the file name



—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-03-01 01:57 UTC, dejanpan commented
@pbaughman I can also fix these 2 things since it is minor?

2019-03-01 03:15 UTC, pbaughman commented
@dejanpan nah, I got it

2019-03-01 14:36 UTC, dejanpan approved these changes

2019-03-01 15:44 UTC, merged